# Generated by Django 4.0.6 on 2022-07-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='app_user',
        ),
    ]
