# Generated by Django 4.0.6 on 2022-07-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=255)),
                ('artist_dob', models.DateField()),
                ('artist_bio', models.CharField(max_length=255)),
            ],
        ),
    ]
