# Generated by Django 4.0.6 on 2022-07-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
